services:
  mysql:
    image: mysql:8.4
    container_name: school_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: bd
      MYSQL_USER: bd
      MYSQL_PASSWORD: linuxlinux
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-prootroot",
        ]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mysql_data:
