services:
  mysql:
    image: mysql:8.0
    container_name: php_project_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bd
      MYSQL_USER: bd
      MYSQL_PASSWORD: linuxlinux
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
